settings:
    title: EasyDocs
    description: 'Welcome to EasyDocs! Use this tool to generate the documentation you need to your hearts content!'
    langauge: en
    encoding: utf-8
    theme: Default
    admin: { admin: '1234' }
    users: { user: '1234' }
    private: false
pages: {  }
