settings:
    title: EasyDocs
    description: 'Welcome to EasyDocs! Use this tool to generate the documentation you need to your hearts content!'
    langauge: en
    encoding: utf-8
    theme: Default
    users: { admin: { password: '1234', role: admin } }
    private: false
pages:
    Documentation: [authentication, docmaker, navigation, requirements, settings, sorter, themebuilder, tool]
