settings:
    title: Docmaker
    description: 'Welcome to Docmaker! Use this tool to generate the documentation you need to your hearts content!'
    langauge: en
    encoding: utf-8
    username: admin
    password: '1234'
    scripts: { local: [js/app.js], external: ['https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js', 'https://cdn.jsdelivr.net/npm/bulma-accordion@2.0.1/dist/js/bulma-accordion.min.js', 'https://cdn.jsdelivr.net/npm/inscrybmde@1.11.6/dist/inscrybmde.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js', 'https://use.fontawesome.com/releases/v5.3.1/js/all.js'] }
    styles: { local: [css/accordion.css, css/styles.css], external: ['https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css', 'https://cdn.jsdelivr.net/npm/bulma-tooltip@3.0.2/dist/css/bulma-tooltip.min.css', 'https://cdn.jsdelivr.net/npm/inscrybmde@1.11.6/dist/inscrybmde.min.css'] }
pages: {  }
